---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_REGION'] || 'us-east-1' %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] || 'us-east-1b' %>
  flavor_id: <%= ENV['AWS_FLAVOR_ID'] || 'm3.medium' %>
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04-ec2
    driver_plugin: ec2
    driver_config:
      image_id: <%=ENV['AWS_UBUNTU_1404_AMI'] %>
      username: ubuntu
  - name: centos-6.5-ec2
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['AWS_CENTOS_65_AMI'] %>
      username: root
      ssh_timeout: 60
      ssh_retries: 5
  - name: amzn-linux-2014.09
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['AWS_AMAZON_201409_AMI'] %>
      username: ec2-user
